name: Backend Testing

on:
  push:
    branches:
      - backend

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: 'academia-ingles'
          MYSQL_USER: ${{ secrets.DatabaseUser }}
          MYSQL_PASSWORD: ${{ secrets.DatabasePassword }}
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection from container 
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"
      - name: Pull repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: backend
      - name: Set Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Setup Database URL
        run: cp .env.ci .env
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache #yarn install
      - name: Push database schema
        run: |
          npx prisma db push
          npx prisma db seed
      - name: Test server
        run: yarn test
