name: Backend Testing

on:
  push:
    branches:
      - backend

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'academia-ingles' # Optional, default value is "test". The specified database which will be create
          mysql root password: root-admin2023 # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: ${{ secrets.DatabaseUser }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
      - name: Pull repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: backend
      - name: Set Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Setup Database URL
        run: | 
          cd ./server
          cp .env.ci .env
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache #yarn install
      - name: Push database schema
        run: |
          npx prisma db push
          npx prisma db seed
      - name: Test server
        run: yarn test
