name: Backend Testing

on:
  push:
    branches:
      - backend

jobs:
  backend-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: 'academia-ingles'
          MYSQL_USER: ${{ secrets.DatabaseUser }}
          MYSQL_PASSWORD: ${{ secrets.DatabasePassword }}
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Pull repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: backend
      - name: Set Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Setup Database URL
        run: cp .env.dev .env
      - name: Push database schema
        run: |
          npx prisma db push
          npx prisma db seed
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache #yarn install
      
      - name: Test server
        run: yarn test
